services:
  bot_db:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: mirodil
      POSTGRES_PASSWORD: 1212
    ports:
      - 5433:5432


  python_bot:
    build:
      context: ./mjtvbot
    ports:
      - "8082:8080"
    depends_on:
      - bot_db
    environment:
      DATABASE_URL: postgres://mirodil:1212@bot_db:5432/telegram_bot?sslmode=disable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

networks:
  default: